# Generated by Django 5.2.8 on 2025-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='communities/pictures/'),
        ),
    ]
